### ISSUE TITLE
List Courses By Name

### ISSUE THREAD

**Issue by albrand** [wilder/fiscaluno-api-documentation#4]
Não é possível listar os cursos por nome de busca do usuário, ex:

https://private-f15175-fiscalunoapi.apiary-mock.com/courses/{{Sistemas de Informação}}

E mesmo que eu tivesse que fazer uma coleta no início da aplicação para buscar por ID, os cursos não tem ID.

**Comment by julioc98** [comment]
O ideal é passar essa informação como um filtro
E se preferirem, posso devolver o resultado de um "LIKE"

**Comment by albrand** [comment]
Cara, eu acho massa a ideia, pq daí os clients servem apenas pra prover as informações e somente isso, eu acho meio errado fazer a req só pra enviar as IDs das instituições...

O Wilder prefere que seja feito desta forma.

**Comment by julioc98** [comment]
Sera implementado o "Like" em pesquisas por nomes de instituições e cursos
